language: java
before_cache:
- ./mvnw build-helper:remove-project-artifact
- find $HOME/.m2/ -type d -name '*-SNAPSHOT' -print0 | xargs -0 rm -rvf
cache:
  directories:
    - $HOME/.m2
matrix:
  include:
    - os: osx
    - os: linux
      env: JDK=openjdk8 deploy=true
    - os: linux
      env: JDK=openjdk8 ARCH=i386
    - os: osx
      env: MAVEN_CONFIG=-Pnative
    - os: linux
      env: MAVEN_CONFIG=-Pnative JDK=openjdk8
    - os: linux
      env: MAVEN_CONFIG=-Pnative JDK=openjdk8 ARCH=i386
sudo: required
install: chmod +x manager && ./manager install
script: ./manager test
