language: java
before_cache:
- ./mvnw build-helper:remove-project-artifact
- find $HOME/.m2/ -type d -name '*-SNAPSHOT' -exec rm -rf {} \; 2>/dev/null
cache:
  directories:
    - $HOME/.m2
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
    - os: linux
      env: JDK=oraclejdk8 deploy=true
    - os: linux
      env: JDK=oraclejdk8 ARCH=i386
    - os: osx
      osx_image: xcode9.4
      env: MAVEN_CONFIG=-Pnative
    - os: linux
      env: MAVEN_CONFIG=-Pnative JDK=oraclejdk8
    - os: linux
      env: MAVEN_CONFIG=-Pnative JDK=oraclejdk8 ARCH=i386
sudo: required
dist: trusty
group: travis_lts
install: chmod +x manager && ./manager install
script: ./manager test
