language: java
before_cache:
- ./mvnw build-helper:remove-project-artifact
- find $HOME/.m2/ -type d -name '*-SNAPSHOT' -exec rm -rf {} \; 2>/dev/null
cache:
  directories:
    - $HOME/.m2
install: true
matrix:
  include:
    - os: osx
    - os: linux
      env: JDK=oraclejdk8
    - os: linux
      env: JDK=oraclejdk8 ARCH=i386
sudo: required
dist: trusty
group: travis_lts
before_script: chmod +x manager && ./manager install
script: ./manager test
